#include "pch.h"
/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p kdeconnect_proxy.h:kdeconnect_proxy.cpp /tmp/combined_kdeconnect.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KDECONNECT_PROXY_H
#define KDECONNECT_PROXY_H


/*
 * Proxy class for interface org.freedesktop.DBus.Introspectable
 */
class OrgFreedesktopDBusIntrospectableInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus.Introspectable"; }

public:
    OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopDBusIntrospectableInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Introspect()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Introspect"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

/*
 * Proxy class for interface org.freedesktop.DBus.Peer
 */
class OrgFreedesktopDBusPeerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus.Peer"; }

public:
    OrgFreedesktopDBusPeerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopDBusPeerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> GetMachineId()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetMachineId"), argumentList);
    }

    inline QDBusPendingReply<> Ping()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Ping"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

/*
 * Proxy class for interface org.freedesktop.DBus.Properties
 */
class OrgFreedesktopDBusPropertiesInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus.Properties"; }

public:
    OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopDBusPropertiesInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusVariant> Get(const QString &interface_name, const QString &property_name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(interface_name) << QVariant::fromValue(property_name);
        return asyncCallWithArgumentList(QStringLiteral("Get"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetAll(const QString &interface_name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(interface_name);
        return asyncCallWithArgumentList(QStringLiteral("GetAll"), argumentList);
    }

    inline QDBusPendingReply<> Set(const QString &interface_name, const QString &property_name, const QDBusVariant &value)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(interface_name) << QVariant::fromValue(property_name) << QVariant::fromValue(value);
        return asyncCallWithArgumentList(QStringLiteral("Set"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void PropertiesChanged(const QString &interface_name, const QVariantMap &changed_properties, const QStringList &invalidated_properties);
};

/*
 * Proxy class for interface org.kde.kdeconnect.daemon
 */
class OrgKdeKdeconnectDaemonInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.daemon"; }

public:
    OrgKdeKdeconnectDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDaemonInterface();

    Q_PROPERTY(QStringList customDevices READ customDevices WRITE setCustomDevices)
    inline QStringList customDevices() const
    { return qvariant_cast< QStringList >(property("customDevices")); }
    inline void setCustomDevices(const QStringList &value)
    { setProperty("customDevices", QVariant::fromValue(value)); }

    Q_PROPERTY(QStringList pairingRequests READ pairingRequests)
    inline QStringList pairingRequests() const
    { return qvariant_cast< QStringList >(property("pairingRequests")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> announcedName()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("announcedName"), argumentList);
    }

    inline QDBusPendingReply<QString> deviceIdByName(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QStringLiteral("deviceIdByName"), argumentList);
    }

    inline QDBusPendingReply<QMap<QString,QString> > deviceNames()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("deviceNames"), argumentList);
    }

    inline QDBusPendingReply<QMap<QString,QString> > deviceNames(bool onlyReachable)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(onlyReachable);
        return asyncCallWithArgumentList(QStringLiteral("deviceNames"), argumentList);
    }

    inline QDBusPendingReply<QMap<QString,QString> > deviceNames(bool onlyReachable, bool onlyPaired)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(onlyReachable) << QVariant::fromValue(onlyPaired);
        return asyncCallWithArgumentList(QStringLiteral("deviceNames"), argumentList);
    }

    inline QDBusPendingReply<QStringList> devices()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("devices"), argumentList);
    }

    inline QDBusPendingReply<QStringList> devices(bool onlyReachable)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(onlyReachable);
        return asyncCallWithArgumentList(QStringLiteral("devices"), argumentList);
    }

    inline QDBusPendingReply<QStringList> devices(bool onlyReachable, bool onlyPaired)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(onlyReachable) << QVariant::fromValue(onlyPaired);
        return asyncCallWithArgumentList(QStringLiteral("devices"), argumentList);
    }

    inline QDBusPendingReply<> forceOnNetworkChange()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("forceOnNetworkChange"), argumentList);
    }

    inline QDBusPendingReply<QString> selfId()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("selfId"), argumentList);
    }

    inline QDBusPendingReply<> sendSimpleNotification(const QString &eventId, const QString &title, const QString &text, const QString &iconName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(eventId) << QVariant::fromValue(title) << QVariant::fromValue(text) << QVariant::fromValue(iconName);
        return asyncCallWithArgumentList(QStringLiteral("sendSimpleNotification"), argumentList);
    }

    inline QDBusPendingReply<> setAnnouncedName(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QStringLiteral("setAnnouncedName"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void announcedNameChanged(const QString &announcedName);
    void customDevicesChanged(const QStringList &customDevices);
    void deviceAdded(const QString &id);
    void deviceListChanged();
    void deviceRemoved(const QString &id);
    void deviceVisibilityChanged(const QString &id, bool isVisible);
    void pairingRequestsChanged();
};

/*
 * Proxy class for interface org.kde.kdeconnect.device
 */
class OrgKdeKdeconnectDeviceInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.device"; }

public:
    OrgKdeKdeconnectDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDeviceInterface();

    Q_PROPERTY(QString iconName READ iconName)
    inline QString iconName() const
    { return qvariant_cast< QString >(property("iconName")); }

    Q_PROPERTY(bool isPairRequested READ isPairRequested)
    inline bool isPairRequested() const
    { return qvariant_cast< bool >(property("isPairRequested")); }

    Q_PROPERTY(bool isPairRequestedByPeer READ isPairRequestedByPeer)
    inline bool isPairRequestedByPeer() const
    { return qvariant_cast< bool >(property("isPairRequestedByPeer")); }

    Q_PROPERTY(bool isPaired READ isPaired)
    inline bool isPaired() const
    { return qvariant_cast< bool >(property("isPaired")); }

    Q_PROPERTY(bool isReachable READ isReachable)
    inline bool isReachable() const
    { return qvariant_cast< bool >(property("isReachable")); }

    Q_PROPERTY(QString name READ name)
    inline QString name() const
    { return qvariant_cast< QString >(property("name")); }

    Q_PROPERTY(int pairState READ pairState)
    inline int pairState() const
    { return qvariant_cast< int >(property("pairState")); }

    Q_PROPERTY(QString statusIconName READ statusIconName)
    inline QString statusIconName() const
    { return qvariant_cast< QString >(property("statusIconName")); }

    Q_PROPERTY(QStringList supportedPlugins READ supportedPlugins)
    inline QStringList supportedPlugins() const
    { return qvariant_cast< QStringList >(property("supportedPlugins")); }

    Q_PROPERTY(QString type READ type)
    inline QString type() const
    { return qvariant_cast< QString >(property("type")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> acceptPairing()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("acceptPairing"), argumentList);
    }

    inline QDBusPendingReply<> cancelPairing()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("cancelPairing"), argumentList);
    }

    inline QDBusPendingReply<QString> encryptionInfo()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("encryptionInfo"), argumentList);
    }

    inline QDBusPendingReply<bool> hasPlugin(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QStringLiteral("hasPlugin"), argumentList);
    }

    inline QDBusPendingReply<bool> isPairRequested()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isPairRequested"), argumentList);
    }

    inline QDBusPendingReply<bool> isPairRequestedByPeer()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isPairRequestedByPeer"), argumentList);
    }

    inline QDBusPendingReply<bool> isPaired()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isPaired"), argumentList);
    }

    inline QDBusPendingReply<bool> isPluginEnabled(const QString &pluginName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(pluginName);
        return asyncCallWithArgumentList(QStringLiteral("isPluginEnabled"), argumentList);
    }

    inline QDBusPendingReply<QStringList> loadedPlugins()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("loadedPlugins"), argumentList);
    }

    inline QDBusPendingReply<int> pairStateAsInt()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("pairStateAsInt"), argumentList);
    }

    inline QDBusPendingReply<QString> pluginIconName(const QString &pluginName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(pluginName);
        return asyncCallWithArgumentList(QStringLiteral("pluginIconName"), argumentList);
    }

    inline QDBusPendingReply<QString> pluginsConfigFile()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("pluginsConfigFile"), argumentList);
    }

    inline QDBusPendingReply<> reloadPlugins()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("reloadPlugins"), argumentList);
    }

    inline QDBusPendingReply<> requestPairing()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("requestPairing"), argumentList);
    }

    inline QDBusPendingReply<> setPluginEnabled(const QString &pluginName, bool enabled)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(pluginName) << QVariant::fromValue(enabled);
        return asyncCallWithArgumentList(QStringLiteral("setPluginEnabled"), argumentList);
    }

    inline QDBusPendingReply<> unpair()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("unpair"), argumentList);
    }

    inline QDBusPendingReply<QByteArray> verificationKey()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("verificationKey"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void nameChanged(const QString &name);
    void pairStateChanged(int pairState);
    void pairingFailed(const QString &error);
    void pluginsChanged();
    void reachableChanged(bool reachable);
    void statusIconNameChanged();
    void typeChanged(const QString &type);
};

/*
 * Proxy class for interface org.kde.kdeconnect.device.contacts
 */
class OrgKdeKdeconnectDeviceContactsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.device.contacts"; }

public:
    OrgKdeKdeconnectDeviceContactsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDeviceContactsInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> synchronizeRemoteWithLocal()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("synchronizeRemoteWithLocal"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void localCacheSynchronized(const QStringList &newContacts);
};

/*
 * Proxy class for interface org.kde.kdeconnect.device.conversations
 */
class OrgKdeKdeconnectDeviceConversationsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.device.conversations"; }

public:
    OrgKdeKdeconnectDeviceConversationsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDeviceConversationsInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QVariantList> activeConversations()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("activeConversations"), argumentList);
    }

    inline QDBusPendingReply<> replyToConversation(qlonglong conversationID, const QString &message, const QVariantList &attachmentUrls)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(conversationID) << QVariant::fromValue(message) << QVariant::fromValue(attachmentUrls);
        return asyncCallWithArgumentList(QStringLiteral("replyToConversation"), argumentList);
    }

    inline QDBusPendingReply<> requestAllConversationThreads()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("requestAllConversationThreads"), argumentList);
    }

    inline QDBusPendingReply<> requestAttachmentFile(qlonglong partID, const QString &uniqueIdentifier)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(partID) << QVariant::fromValue(uniqueIdentifier);
        return asyncCallWithArgumentList(QStringLiteral("requestAttachmentFile"), argumentList);
    }

    inline QDBusPendingReply<> requestConversation(qlonglong conversationID, int start, int end)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(conversationID) << QVariant::fromValue(start) << QVariant::fromValue(end);
        return asyncCallWithArgumentList(QStringLiteral("requestConversation"), argumentList);
    }

    inline QDBusPendingReply<> sendWithoutConversation(const QVariantList &addressList, const QString &message, const QVariantList &attachmentUrls)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(addressList) << QVariant::fromValue(message) << QVariant::fromValue(attachmentUrls);
        return asyncCallWithArgumentList(QStringLiteral("sendWithoutConversation"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void attachmentReceived(const QString &filePath, const QString &fileName);
    void conversationCreated(const QDBusVariant &msg);
    void conversationLoaded(qlonglong conversationID, qulonglong messageCount);
    void conversationRemoved(qlonglong conversationID);
    void conversationUpdated(const QDBusVariant &msg);
};

/*
 * Proxy class for interface org.kde.kdeconnect.device.sms
 */
class OrgKdeKdeconnectDeviceSmsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.device.sms"; }

public:
    OrgKdeKdeconnectDeviceSmsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDeviceSmsInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> getAttachment(qlonglong partID, const QString &uniqueIdentifier)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(partID) << QVariant::fromValue(uniqueIdentifier);
        return asyncCallWithArgumentList(QStringLiteral("getAttachment"), argumentList);
    }

    inline QDBusPendingReply<> launchApp()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("launchApp"), argumentList);
    }

    inline QDBusPendingReply<> requestAllConversations()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("requestAllConversations"), argumentList);
    }

    inline QDBusPendingReply<> requestAttachment(qlonglong partID, const QString &uniqueIdentifier)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(partID) << QVariant::fromValue(uniqueIdentifier);
        return asyncCallWithArgumentList(QStringLiteral("requestAttachment"), argumentList);
    }

    inline QDBusPendingReply<> requestConversation(qlonglong conversationID)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(conversationID);
        return asyncCallWithArgumentList(QStringLiteral("requestConversation"), argumentList);
    }

    inline QDBusPendingReply<> requestConversation(qlonglong conversationID, qlonglong rangeStartTimestamp)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(conversationID) << QVariant::fromValue(rangeStartTimestamp);
        return asyncCallWithArgumentList(QStringLiteral("requestConversation"), argumentList);
    }

    inline QDBusPendingReply<> requestConversation(qlonglong conversationID, qlonglong rangeStartTimestamp, qlonglong numberToRequest)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(conversationID) << QVariant::fromValue(rangeStartTimestamp) << QVariant::fromValue(numberToRequest);
        return asyncCallWithArgumentList(QStringLiteral("requestConversation"), argumentList);
    }

    inline QDBusPendingReply<> sendSms(const QVariantList &addresses, const QString &textMessage, const QVariantList &attachmentUrls)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(addresses) << QVariant::fromValue(textMessage) << QVariant::fromValue(attachmentUrls);
        return asyncCallWithArgumentList(QStringLiteral("sendSms"), argumentList);
    }

    inline QDBusPendingReply<> sendSms(const QVariantList &addresses, const QString &textMessage, const QVariantList &attachmentUrls, qlonglong subID)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(addresses) << QVariant::fromValue(textMessage) << QVariant::fromValue(attachmentUrls) << QVariant::fromValue(subID);
        return asyncCallWithArgumentList(QStringLiteral("sendSms"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

/*
 * Proxy class for interface org.kde.kdeconnect.device.telephony
 */
class OrgKdeKdeconnectDeviceTelephonyInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kdeconnect.device.telephony"; }

public:
    OrgKdeKdeconnectDeviceTelephonyInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKdeconnectDeviceTelephonyInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void callReceived(const QString &event, const QString &number, const QString &contactName);
};

namespace org {
  namespace freedesktop {
    namespace DBus {
      using Introspectable = ::OrgFreedesktopDBusIntrospectableInterface;
      using Peer = ::OrgFreedesktopDBusPeerInterface;
      using Properties = ::OrgFreedesktopDBusPropertiesInterface;
    }
  }
  namespace kde {
    namespace kdeconnect {
      using daemon = ::OrgKdeKdeconnectDaemonInterface;
      using device = ::OrgKdeKdeconnectDeviceInterface;
//       namespace device {
        using contacts = ::OrgKdeKdeconnectDeviceContactsInterface;
        using conversations = ::OrgKdeKdeconnectDeviceConversationsInterface;
        using sms = ::OrgKdeKdeconnectDeviceSmsInterface;
        using telephony = ::OrgKdeKdeconnectDeviceTelephonyInterface;
//       }
    }
  }
}
#endif
