/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p kdeconnect_proxy.h:kdeconnect_proxy.cpp /tmp/combined_kdeconnect.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "kdeconnect_proxy.h"

/*
 * Implementation of interface class OrgFreedesktopDBusIntrospectableInterface
 */

OrgFreedesktopDBusIntrospectableInterface::OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusIntrospectableInterface::~OrgFreedesktopDBusIntrospectableInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusPeerInterface
 */

OrgFreedesktopDBusPeerInterface::OrgFreedesktopDBusPeerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPeerInterface::~OrgFreedesktopDBusPeerInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusPropertiesInterface
 */

OrgFreedesktopDBusPropertiesInterface::OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPropertiesInterface::~OrgFreedesktopDBusPropertiesInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDaemonInterface
 */

OrgKdeKdeconnectDaemonInterface::OrgKdeKdeconnectDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDaemonInterface::~OrgKdeKdeconnectDaemonInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDeviceInterface
 */

OrgKdeKdeconnectDeviceInterface::OrgKdeKdeconnectDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDeviceInterface::~OrgKdeKdeconnectDeviceInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDeviceBatteryInterface
 */

OrgKdeKdeconnectDeviceBatteryInterface::OrgKdeKdeconnectDeviceBatteryInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDeviceBatteryInterface::~OrgKdeKdeconnectDeviceBatteryInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDeviceConversationsInterface
 */

OrgKdeKdeconnectDeviceConversationsInterface::OrgKdeKdeconnectDeviceConversationsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDeviceConversationsInterface::~OrgKdeKdeconnectDeviceConversationsInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDeviceSmsInterface
 */

OrgKdeKdeconnectDeviceSmsInterface::OrgKdeKdeconnectDeviceSmsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDeviceSmsInterface::~OrgKdeKdeconnectDeviceSmsInterface()
{
}

/*
 * Implementation of interface class OrgKdeKdeconnectDeviceTelephonyInterface
 */

OrgKdeKdeconnectDeviceTelephonyInterface::OrgKdeKdeconnectDeviceTelephonyInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKdeconnectDeviceTelephonyInterface::~OrgKdeKdeconnectDeviceTelephonyInterface()
{
}

